# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/etc/mongo

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: database
  #     ME_CONFIG_MONGODB_PORT: 27017
  #   links:
  #     - mongo

volumes:
  mongodb-volume: