version: '3'
services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-volume:/etc/mysql/conf.d/
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  # adminer:
  #   image: adminer
  #   container_name: adminer-container
  #   ports:
  #     - 8080:8080

volumes:
  mysql-volume:
  