version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sql-server-container
    volumes:
      - sqlserver-volume:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y -
      MSSQL_SA_PASSWORD: "database"
volumes:
  sqlserver-volume:
